const FieldTable = {
    "avg_rating": true,
    "backup_location": true,
    "btih": true,
    "call_number": true,
    "collection": true,
    "contributor": true,
    "coverage": true,
    "creator": true,
    "date": true,
    "description": true,
    "downloads": true,
    "external-identifier": true,
    "foldoutcount": true,
    "format": true,
    "genre": true,
    "identifier": true,
    "imagecount": true,
    "indexflag": true,
    "item_size": true,
    "language": true,
    "licenseurl": true,
    "mediatype": true,
    "members": true,
    "month": true,
    "name": true,
    "noindex": true,
    "num_reviews": true,
    "oai_updatedate": true,
    "publicdate": true,
    "publisher": true,
    "related-external-id": true,
    "reviewdate": true,
    "rights": true,
    "scanningcentre": true,
    "source": true,
    "stripped_tags": true,
    "subject": true,
    "title": true,
    "type": true,
    "volume": true,
    "week": true,
    "year": true
}

export { FieldTable }