name: CICD
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # https://velociraptor.run/docs/github-actions/
    - uses: jurassiscripts/setup-velociraptor@v2
    - run: |
        cat /etc/issue
        # for coverage
        apt-get install -yqq lcov
        # for script command
        # apk add util-linux

        vr lint
        vr test
