name: CICD
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      # https://github.com/denoland/deno_docker
      image: denoland/deno:alpine
    steps:
    - uses: actions/checkout@v3
    - run: |
        deno install -qAn vr https://deno.land/x/velociraptor/cli.ts
        # for coverage
        apk add lcov --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
        # for script command
        apk add util-linux

        vr lint
        vr test
