name: CICD
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      # https://github.com/internetarchive/dyno
      image: ghcr.io/internetarchive/dyno:main
    steps:
    - uses: actions/checkout@v2
    - run: /app/lint
