name: CICD
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      # https://github.com/denoland/deno_docker
      image: https://hub.docker.com/r/denoland/deno
    steps:
    - uses: actions/checkout@v2
    - run: |
        deno install -qAn vr https://deno.land/x/velociraptor/cli.ts
        vr lint
        vr test
